env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - off
    - unix
  no-case-declarations:
    - off
  no-console:
    - off
  quotes:
    - error
    - single
  semi:
    - error
    - always
