(in-package #:liutos.cli.misc)

(defun get-machine-id ()
  "Return an ID generated by this machine's private IP address."
  (let* ((private-ip-address-vector (get-private-ip))
         (private-ip-address (ip-vector-to-number private-ip-address-vector)))
    (logand private-ip-address #2R1111111111)))

(defun get-random-id ()
  "Return a 12 bits random integer."
  (random (1+ #2R111111111111)))

(defun get-ts ()
  "Return a 41 bits timestamp."
  (logand (now :millisecond) 9223372036854775807))

(defun snowflake ()
  "Return an integer generated by the Twitter snowflake algorithm.

The algorithm is descripted in this [post](http://www.lanindex.com/twitter-snowflake，64位自增id算法详解/)."
  (let ((ts (get-ts))
        (machine-id (get-machine-id))
        (random-id (get-random-id)))
    (logior (ash 0 63)
            (ash ts 22)
            (ash machine-id 12)
            random-id)))
